### ISSUE TITLE
memory usage not showing

### ISSUE THREAD

**Issue by Globegitter** [seripap/vscode-memory#1]
Hi, I just installed the plugin on VS Code 1.35.1 on Elementary OS 5 (Ubuntu 18.04) and for some reason the memory usage is not showing. Is there anything I have to do to activate it?

**Comment by seripap** [comment]
Hi, sorry for the late reply. The extension should activate automatically upon installation. To help debug, when you enable the extension, are you getting any errors? (`Output` 
Panel --> `Extensions` (via dropdown))

![Screen Shot 2019-08-05 at 2 41 56 PM](https://user-images.githubusercontent.com/683200/62487181-3215b300-b78f-11e9-96bc-26cfc216dfa6.png)

On another note, this package uses `find-process` and `pidusage` as dependencies to gather information. They both should be supported on Linux but I cannot be 100% certain.
